### ISSUE TITLE
Indentation error

### ISSUE THREAD

**Issue by gofornaman** [mjk188/ASL-Translator#1]
File "ASL.py", line 39
    temp+=1
          ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by gofornaman** [comment]
That has been solved but when I run ASL.py now, I get this error

.
.
Class Q is being loaded
SVM is building wait some time ...
6800
6800
Enter Camera number: 1
OpenCV Error: Sizes of input arguments do not match (The lower bounary is neither an array of the same size and same type as src, nor a scalar) in cv::inRange, file ..\..\..\modules\core\src\arithm.cpp, line 2703
Traceback (most recent call last):
  File "ASL.py", line 29, in <module>
    mask = cv2.inRange(blur, skin_ycrcb_min, skin_ycrcb_max)  # detecting the hand in the bounding box using skin detection
cv2.error: ..\..\..\modules\core\src\arithm.cpp:2703: error: (-209) The lower bounary is neither an array of the same size and same type as src, nor a scalar in function cv::inRange

Please help me out

**Comment by VineethVasudevan** [comment]
how did you remove the indentation error? And it gives me an error on line 37.
Help me out!!

**Comment by abdullahmujahidali** [comment]
try a online code formatter. worked for me
