### ISSUE TITLE
this error while running asl.py in python 3.1

### ISSUE THREAD

**Issue by rakshit2711** [mjk188/ASL-Translator#4]
Class Q is being loaded
Class Q is being loaded
Class Q is being loaded
Class Q is being loaded
Class Q is being loaded
SVM is building wait some time ...
6800
6800
Traceback (most recent call last):
  File "ASL.py", line 6, in <module>
    model=st.trainSVM(17)
  File "C:\Users\Rakshit\Desktop\ASL-Translator-master\ASL-Translator-master\svm_train.py", line 82, in trainSVM
    model = SVM(C=2.67, gamma=5.383)
  File "C:\Users\Rakshit\Desktop\ASL-Translator-master\ASL-Translator-master\svm_train.py", line 14, in __init__
    self.model = cv2.SVM()
AttributeError: module 'cv2.cv2' has no attribute 'SVM'

**Comment by khushboo097** [comment]
replace it with cv2.ml.SVM_create() according to latest opencv version
