### ISSUE TITLE
cv2.cv2

### ISSUE THREAD

**Issue by Abdulsemedsomi** [mjk188/ASL-Translator#6]
Traceback (most recent call last):
  File "C:/Users/Abdulsemed Mohammed/Downloads/Compressed/ASL-Translator-master/ASL-Translator-master/ASL.py", line 3, in <module>
    import util as ut
  File "C:\Users\Abdulsemed Mohammed\Downloads\Compressed\ASL-Translator-master\ASL-Translator-master\util.py", line 3, in <module>
    import svm_train as st
  File "C:\Users\Abdulsemed Mohammed\Downloads\Compressed\ASL-Translator-master\ASL-Translator-master\svm_train.py", line 6, in <module>
    svm_params = dict(kernel_type=cv2.SVM_RBF,
AttributeError: module 'cv2.cv2' has no attribute 'SVM_RBF'

**Comment by ad4013** [comment]
use cv2.ml.SVM_BRF
