### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by prashanthaldiyal** [mjk188/ASL-Translator#8]
Traceback (most recent call last):
  File "ASL.py", line 6, in <module>
    model=st.trainSVM(17)
  File "C:\Users\Wall-E\Desktop\n\svm_train.py", line 85, in trainSVM
    model.train(samples, labels)  # features trained against the labels using svm
  File "C:\Users\Wall-E\Desktop\n\svm_train.py", line 23, in train
    self.model.train(samples, responses,params=svm_params) # inbuilt training function
TypeError: only size-1 arrays can be converted to Python scalars

**Comment by abdullahmujahidali** [comment]
self.model.train(samples, cv2.ml.ROW_SAMPLE, responses)

use this.
